// <auto-generated />
namespace Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Country_And_TPC_Mapping : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Country_And_TPC_Mapping));
        
        string IMigrationMetadata.Id
        {
            get { return "201811091348009_Country_And_TPC_Mapping"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
